FROM python:3.12-slim-bookworm

# Install system dependencies for USB webcam support (e.g., v4l2)
# Install dependencies
RUN apt-get update && apt-get install -y \
	  bash \
      libopencv-dev \
      libv4l-dev \
      v4l-utils \
      ffmpeg \
      mc \
      && apt-get clean

WORKDIR /app

ENV DISPLAY=:0
ENV QT_X11_NO_MITSHM=1
ENV QT_DEBUG_PLUGINS=1

COPY requirements.txt .
# Install any extra Python dependencies
RUN pip3 install -r requirements.txt

# Copy necessary files
COPY face_landmarker_v2_with_blendshapes.task .
COPY cam2flowise.py .
COPY .env .

# Run the script
#CMD ["python3", "capture.py"]}


